services:
  board-api:
    container_name: board-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:debug"]
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Seoul
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=anonymous_board
    volumes:
      - .:/app

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3305:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./db/scripts:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mysql_data:
